name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Kódbázis klónozása
        uses: actions/checkout@v2

      - name: Python beállítása
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Függőségek telepítése
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyyaml

      - name: Tesztek futtatása
        run: |
          python -m unittest discover -s tests -p "test_*.py"

      - name: Adatfeldolgozás futtatása
        run: |
          python src/data_pipeline.py

      - name: Modell betanítása és mentése
        run: |
          python models/model_pipeline.py

      - name: API tesztelése
        run: |
          nohup uvicorn main:app --host 127.0.0.1 --port 8000 &
          sleep 5
          response=$(curl -s -X POST "http://127.0.0.1:8000/predict" \
          -H "Content-Type: application/json" \
          -d '{"Pregnancies": 8, "Glucose": 190, "BloodPressure": 90, "SkinThickness": 40, "Insulin": 200, "BMI": 35.0, "DiabetesPedigreeFunction": 1.2, "Age": 60}')
          echo "Response: $response"
          echo "$response" | grep '"prediction":1'

      - name: API leállítása
        run: |
          pkill uvicorn
